// This file will be auto-generated by Supabase CLI once connected.
// For now, we define the types manually matching our schema.

export type AppRole = 'super_admin' | 'hr_admin' | 'payroll_admin' | 'manager' | 'employee'

export interface OrganizationSettings {
  modules: {
    leave: boolean
    attendance: boolean
    payroll: boolean
    recruitment: boolean
    performance: boolean
    learning: boolean
  }
  working_days: number[]
  date_format: string
  default_probation_months: number
  default_notice_days: number
  week_start_day: number
  role_permissions?: Record<string, string[]>
}

export interface Organization {
  id: string
  name: string
  slug: string
  logo_url: string | null
  domain: string | null
  address: Record<string, string> | null
  phone: string | null
  email: string | null
  website: string | null
  industry: string | null
  employee_count_range: string | null
  fiscal_year_start: number
  timezone: string
  currency: string
  settings: OrganizationSettings
  created_at: string
  updated_at: string
}

export interface Profile {
  id: string
  organization_id: string | null
  email: string
  first_name: string | null
  last_name: string | null
  avatar_url: string | null
  role: AppRole
  is_active: boolean
  created_at: string
  updated_at: string
}

export interface Department {
  id: string
  organization_id: string
  name: string
  code: string | null
  description: string | null
  parent_department_id: string | null
  head_employee_id: string | null
  is_active: boolean
  created_at: string
  updated_at: string
}

export interface Designation {
  id: string
  organization_id: string
  title: string
  level: number | null
  description: string | null
  is_active: boolean
  created_at: string
}

export interface Employee {
  id: string
  organization_id: string
  profile_id: string | null
  employee_code: string | null
  first_name: string
  last_name: string
  email: string
  personal_email: string | null
  phone: string | null
  date_of_birth: string | null
  gender: string | null
  marital_status: string | null
  blood_group: string | null
  department_id: string | null
  designation_id: string | null
  reporting_manager_id: string | null
  employment_type: string
  date_of_joining: string | null
  date_of_leaving: string | null
  probation_end_date: string | null
  status: string
  current_address: Record<string, string> | null
  permanent_address: Record<string, string> | null
  pan_number: string | null
  aadhar_number: string | null
  passport_number: string | null
  bank_details: Record<string, string> | null
  emergency_contact: Record<string, string> | null
  avatar_url: string | null
  created_at: string
  updated_at: string
}

export interface EmployeeWithRelations extends Employee {
  department?: Department | null
  designation?: Designation | null
  reporting_manager?: Pick<Employee, 'id' | 'first_name' | 'last_name'> | null
}

export interface LeaveType {
  id: string
  organization_id: string
  name: string
  code: string | null
  description: string | null
  default_days: number
  is_carry_forward: boolean
  max_carry_forward_days: number
  is_paid: boolean
  is_active: boolean
  applicable_gender: string | null
  created_at: string
}

export interface LeaveBalance {
  id: string
  employee_id: string
  leave_type_id: string
  year: number
  total_days: number
  used_days: number
  pending_days: number
  carried_forward_days: number
}

export interface LeaveRequest {
  id: string
  organization_id: string
  employee_id: string
  leave_type_id: string
  start_date: string
  end_date: string
  total_days: number
  reason: string | null
  status: 'pending' | 'approved' | 'rejected' | 'cancelled'
  approved_by: string | null
  approved_at: string | null
  rejection_reason: string | null
  attachment_url: string | null
  created_at: string
  updated_at: string
}

export interface AttendanceRecord {
  id: string
  organization_id: string
  employee_id: string
  date: string
  clock_in: string | null
  clock_out: string | null
  shift_id: string | null
  status: string
  work_hours: number | null
  overtime_hours: number
  notes: string | null
  is_regularized: boolean
  created_at: string
  updated_at: string
}

export interface Shift {
  id: string
  organization_id: string
  name: string
  start_time: string
  end_time: string
  grace_period_minutes: number
  is_default: boolean
  is_active: boolean
  created_at: string
}

export interface Holiday {
  id: string
  organization_id: string
  name: string
  date: string
  type: string
  is_active: boolean
  created_at: string
}

export interface Announcement {
  id: string
  organization_id: string
  title: string
  content: string | null
  priority: string
  target_departments: string[] | null
  published_by: string | null
  is_active: boolean
  published_at: string
  expires_at: string | null
  created_at: string
}

export interface Notification {
  id: string
  organization_id: string
  user_id: string
  title: string
  message: string | null
  type: string | null
  reference_type: string | null
  reference_id: string | null
  is_read: boolean
  created_at: string
}

export interface Document {
  id: string
  organization_id: string
  employee_id: string | null
  name: string
  type: string | null
  file_url: string
  file_size: number | null
  uploaded_by: string | null
  created_at: string
}

export interface ActivityLog {
  id: string
  organization_id: string
  user_id: string | null
  action: string
  entity_type: string | null
  entity_id: string | null
  metadata: Record<string, unknown> | null
  created_at: string
}

// Supabase Database type (simplified for manual use)
export interface Database {
  public: {
    Tables: {
      organizations: { Row: Organization; Insert: Partial<Organization>; Update: Partial<Organization> }
      profiles: { Row: Profile; Insert: Partial<Profile>; Update: Partial<Profile> }
      departments: { Row: Department; Insert: Partial<Department>; Update: Partial<Department> }
      designations: { Row: Designation; Insert: Partial<Designation>; Update: Partial<Designation> }
      employees: { Row: Employee; Insert: Partial<Employee>; Update: Partial<Employee> }
      leave_types: { Row: LeaveType; Insert: Partial<LeaveType>; Update: Partial<LeaveType> }
      leave_balances: { Row: LeaveBalance; Insert: Partial<LeaveBalance>; Update: Partial<LeaveBalance> }
      leave_requests: { Row: LeaveRequest; Insert: Partial<LeaveRequest>; Update: Partial<LeaveRequest> }
      attendance_records: { Row: AttendanceRecord; Insert: Partial<AttendanceRecord>; Update: Partial<AttendanceRecord> }
      shifts: { Row: Shift; Insert: Partial<Shift>; Update: Partial<Shift> }
      holidays: { Row: Holiday; Insert: Partial<Holiday>; Update: Partial<Holiday> }
      announcements: { Row: Announcement; Insert: Partial<Announcement>; Update: Partial<Announcement> }
      notifications: { Row: Notification; Insert: Partial<Notification>; Update: Partial<Notification> }
      documents: { Row: Document; Insert: Partial<Document>; Update: Partial<Document> }
      activity_log: { Row: ActivityLog; Insert: Partial<ActivityLog>; Update: Partial<ActivityLog> }
    }
  }
}
